default: &default
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  pool: 10
  host: 127.0.0.1
  username: bhuser
  password: "363099"

development:
  <<: *default
  database: cell_dev

test:
  <<: *default
  encoding: utf8
  database: cell_test

qa:
  <<: *default

production:
  <<: *default
  database: cell_pd
  username:
  password:
  host: